### ISSUE TITLE
global: click 8.0.0 breaking changes

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana#503]
`click` version `8.0.0` brings lots of major changes, all the information related can be consulted here: https://github.com/pallets/click/releases/tag/8.0.0

For instance `reana-dev run-ci` is broken when installing this version.

```console
$ reana-dev run-ci -m /var/reana:/var/reana --exclude-components=r-a-vomsproxy,r-a-krb5 -c r-d-helloworld --admin-email admin@reana.io --admin-password ***** --mode debug
Traceback (most recent call last):
  File "/Users/marco/.virtualenvs/r/bin/reana-dev", line 33, in <module>
    sys.exit(load_entry_point('reana', 'console_scripts', 'reana-dev')())
  File "/Users/marco/.virtualenvs/r/bin/reana-dev", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/marco/.pyenv/versions/3.8.2/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/marco/.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/marco/code/reanahub/reana/reana/reana_dev/cli.py", line 14, in <module>
    from reana.reana_dev.cluster import cluster_commands_list
  File "/Users/marco/code/reanahub/reana/reana/reana_dev/cluster.py", line 180, in <module>
    def cluster_build(
  File "/Users/marco/.virtualenvs/r/lib/python3.8/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/marco/.virtualenvs/r/lib/python3.8/site-packages/click/core.py", line 2467, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/Users/marco/.virtualenvs/r/lib/python3.8/site-packages/click/core.py", line 2106, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.
```

We have `click` as dependency in many repos, none of them upper pinning the version:
- `reana`: https://github.com/reanahub/reana/blob/2c5df09dc9f6fa02e0321330ec79af9bbe480a0d/setup.py#L38
- `reana-client`: https://github.com/reanahub/reana-client/blob/fcb97aa0a31bc43122826b04fc81806775c603e5/setup.py#L45
- `pytest-reana`: https://github.com/reanahub/pytest-reana/blob/18381ca19f915c2848bb86109c4c1d7fa9274163/setup.py#L40
- `reana-commons`: https://github.com/reanahub/reana-commons/blob/8ec34bb035722041a5aed13bc240f40962605967/setup.py#L45
- reana-workflow-engine-cwl/setup.py
44:    "click>=7",
- reana-workflow-engine-yadage/setup.py
45:    "click>=7",
- reana-workflow-engine-serial/setup.py
42:    "click>=7",

As a quick workaround, we can pin version <8.0, but ideally, we should change what's needed to keep the latest version in all our repos and test that every works fine.

**Comment by mvidalgarcia** [comment]
Apparently, what's breaking `reana-dev` is the following:

> The default value for a parameter with nargs > 1 and multiple=True must be a list of tuples. #1649

More info here: https://click.palletsprojects.com/en/8.0.x/options/?highlight=multiple#multiple-options

> When passing a default with multiple=True, the default value must be a list or tuple, otherwise it will be interpreted as a list of single characters.
> `@click.option("--format", multiple=True, default=["json"])`
