### ISSUE TITLE
test: run full CWL conformance test with latest cwltest

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#52]
Use reanahub/reana-client#77 and reanahub/reana-workflow-engine-cwl#25.

**Comment by tiborsimko** [comment]
Here's the recipe:
- https://github.com/reanahub/reana-workflow-engine-cwl/pull/19/files#r171526019

**Comment by dinosk** [comment]
In my machine this didn't work, I had to do some modifications in the run_test.sh script to get them to run, all jobs succeed but the tests fail because there is no output returned.

Running in verbose mode I get stuff like this:
```
[job tmap-tool.cwl] /Users/dinossimpson/CERN/reanahub/common-workflow-language/v1.0BpVG80bK0I_i$ docker \
    run \
    -i \
    --volume=/Users/dinossimpson/CERN/reanahub/common-workflow-language/v1.0BpVG80bK0I_i:/private/var/spool/cwl:rw \
    --volume=/Users/dinossimpson/CERN/reanahub/common-workflow-language/v1.0BpVG803QDHp5:/tmp:rw \
    --volume=/Users/dinossimpson/CERN/reanahub/common-workflow-language/v1.0/v1.0/reads.fastq:/private/var/lib/cwl/stg1ab31961-1c9b-4cc1-9a37-ee1ab81a5299/reads.fastq:ro \
    --volume=/Users/dinossimpson/CERN/reanahub/common-workflow-language/v1.0/v1.0/args.py:/private/var/lib/cwl/stgf07a358d-ed1a-4930-ac59-f333516ce4f2/args.py:ro \
    --workdir=/private/var/spool/cwl \
    --read-only=true \
    --user=501:20 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/private/var/spool/cwl \
    python:2-slim \
    python \
    /private/var/lib/cwl/stgf07a358d-ed1a-4930-ac59-f333516ce4f2/args.py \
    tmap \
    mapall \
    stage1 \
    map1 \
    --min-seq-length \
    20 \
    map2 \
    --min-seq-length \
    20 \
    stage2 \
    map1 \
    --max-seq-length \
    20 \
    --min-seq-length \
    10 \
    --seed-length \
    16 \
    map2 \
    --max-seed-hits \
    -1 \
    --max-seq-length \
    20 \
    --min-seq-length \
    10
[job tmap-tool.cwl] completed success
Final process status is success
need more than 1 value to unpack
None
None
Test failed: cwltool --tmp-outdir-prefix=/Users/dinossimpson/CERN/reanahub/common-workflow-language/v1.0BpVG80 --tmpdir-prefix=/Users/dinossimpson/CERN/reanahub/common-workflow-language/v1.0BpVG80 --outdir=/Users/dinossimpson/CERN/reanahub/common-workflow-language/v1.0BpVG80 v1.0/tmap-tool.cwl v1.0/tmap-job.json
Test nested command line bindings
Compare failure expected: {
    "args": [
        "tmap", 
        "mapall", 
        "stage1", 
        "map1", 
        "--min-seq-length", 
        "20", 
        "map2", 
        "--min-seq-length", 
        "20", 
        "stage2", 
        "map1", 
        "--max-seq-length", 
        "20", 
        "--min-seq-length", 
        "10", 
        "--seed-length", 
        "16", 
        "map2", 
        "--max-seed-hits", 
        "-1", 
        "--max-seq-length", 
        "20", 
        "--min-seq-length", 
        "10"
    ]
}
got: {}
caused by: failed comparison for key 'args': expected: [
    "tmap", 
    "mapall", 
    "stage1", 
    "map1", 
    "--min-seq-length", 
    "20", 
    "map2", 
    "--min-seq-length", 
    "20", 
    "stage2", 
    "map1", 
    "--max-seq-length", 
    "20", 
    "--min-seq-length", 
    "10", 
    "--seed-length", 
    "16", 
    "map2", 
    "--max-seed-hits", 
    "-1", 
    "--max-seq-length", 
    "20", 
    "--min-seq-length", 
    "10"
]
got: null
```

**Comment by diegodelemos** [comment]
> Use reanahub/reana-client#77 and reanahub/reana-workflow-engine-cwl#25.

Using this PRs I can not manage to have it working as before:

```console
$ ./run_test.sh RUNNER=reana-cwl-runner
--- Running conformance test v1.0 on /Users/rodrigdi/.virtualenvs/reana-client/bin/reana-cwl-runner ---
reana-cwl-runner, version 0.1.0.dev20180201
Test [1/127]
Test failed: /Users/rodrigdi/.virtualenvs/reana-client/bin/reana-cwl-runner --outdir=/var/folders/2d/9ksq4t3n2_33gz12g4q_ndm80000gn/T/tmpn__Xdr --quiet v1.0/bwa-mem-tool.cwl v1.0/bwa-mem-job.json
General test of command line generation
Returned non-zero
Traceback (most recent call last):
  File "/Users/rodrigdi/.virtualenvs/reana-client/bin/reana-cwl-runner", line 11, in <module>
    load_entry_point('reana-client', 'console_scripts', 'reana-cwl-runner')()
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: cwl_runner() got multiple values for keyword argument 'quiet'

Test [2/127]
Test failed: /Users/rodrigdi/.virtualenvs/reana-client/bin/reana-cwl-runner --outdir=/var/folders/2d/9ksq4t3n2_33gz12g4q_ndm80000gn/T/tmpoHDsNp --quiet v1.0/binding-test.cwl v1.0/bwa-mem-job.json
Test nested prefixes with arrays
Returned non-zero
Traceback (most recent call last):
  File "/Users/rodrigdi/.virtualenvs/reana-client/bin/reana-cwl-runner", line 11, in <module>
    load_entry_point('reana-client', 'console_scripts', 'reana-cwl-runner')()
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rodrigdi/.virtualenvs/reana-client/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: cwl_runner() got multiple values for keyword argument 'quiet'
```

Have you seen this before @anton-khodak ?

**Comment by dinosk** [comment]
With the latest changes I get: 116 tests passed, 11 failures, 0 unsupported features

**Comment by anton-khodak** [comment]
Please send me your output log

**Comment by dinosk** [comment]
@anton-khodak sorry for not replying, I had switched from this task and saw this quite late. The final count was 126/127 conformance tests passing (#20 fails for some reason, the one with the `any` wildcard)  which allows for continuing with the merging :)
